### ISSUE TITLE
Crash on version 1.4.2

### ISSUE THREAD

**Issue by jairobjunior** [emaloney/CleanroomASL#13]
Hey guys, 

My version just bumped from 1.4.1 to 1.4.2 and when I call `Log.enable()` I get a fatal_error on `ASLLogRecorder` line 98. Here is the stack trace:

```
dyld: lazy symbol binding failed: Symbol not found: __TIFC12CleanroomASL9ASLClientcFT6senderGSqSS_8facilityGSqSS_10filterMaskVs5Int3212useRawStdErrSb7optionsVS0_7Options_S0_A_
  Referenced from: .../CoreSimulator/Devices/06DB0BD4-2185-4D11-86A9-E6F714446D5D/data/Containers/Bundle/Application/5ECD4AAD-169A-4BF7-871E-1BBC96A67CCE/app/Frameworks/CleanroomLogger.framework/CleanroomLogger
  Expected in: .../CoreSimulator/Devices/06DB0BD4-2185-4D11-86A9-E6F714446D5D/data/Containers/Bundle/Application/5ECD4AAD-169A-4BF7-871E-1BBC96A67CCE/app/Frameworks/CleanroomASL.framework/CleanroomASL

dyld: Symbol not found: __TIFC12CleanroomASL9ASLClientcFT6senderGSqSS_8facilityGSqSS_10filterMaskVs5Int3212useRawStdErrSb7optionsVS0_7Options_S0_A_
  Referenced from: ~/Library/Developer/CoreSimulator/Devices/06DB0BD4-2185-4D11-86A9-E6F714446D5D/data/Containers/Bundle/Application/5ECD4AAD-169A-4BF7-871E-1BBC96A67CCE/app/Frameworks/CleanroomLogger.framework/CleanroomLogger
  Expected in: ~/Library/Developer/CoreSimulator/Devices/06DB0BD4-2185-4D11-86A9-E6F714446D5D/data/Containers/Bundle/Application/5ECD4AAD-169A-4BF7-871E-1BBC96A67CCE/app/Frameworks/CleanroomASL.framework/CleanroomASL
```

I had to force back to the previous version on my carthage file...

```
github "emaloney/CleanroomASL" == 1.4.1
github "emaloney/CleanroomLogger" == 2.1.0
```

But I would like to leave `~>` flexible for the changes.

Thank you for maintaining the project though. 👍

**Comment by emaloney** [comment]
Thanks for the report. You might need to update both CleanroomLogger (now 2.1.3) and CleanroomASL to the latest releases to avoid this issue. Also, it's possible something isn't rebuilding, so just to be safe maybe kill your DerivedData directory.

Please let me know if any of that works for you.

**Comment by emaloney** [comment]
I've published another release since then; we're now at version 2.1.4.

Am curious you're having any trouble with that one, too.

**Comment by emaloney** [comment]
Will assume everything's OK unless I hear back. Please re-open the ticket if so.
