### ISSUE TITLE
Swift 3 branch: compiler error

### ISSUE THREAD

**Issue by jberkel** [emaloney/CleanroomASL#14]
```
CleanroomASL/Sources/ASLClient.swift:298:41: error: closure use of non-escaping parameter 'callback' may allow it to escape
```

Xcode 8 GM

**Comment by emaloney** [comment]
Thanks for the report.

**Comment by emaloney** [comment]
Pushed a fix to the `swift3` branch. Please confirm that it is working on your end.

Thanks,
E.

**Comment by jberkel** [comment]
Sure, will do. Can you update CleanroomLogger to point to this version?

**Comment by jberkel** [comment]
(it compiles fine on it's own but still getting error when I pull in CleanroomLogger, since it is locked to the older version)

**Comment by emaloney** [comment]
Yes, although I should warn you that it will include some changes to how CleanroomASL is integrated that I've also had queued up.

**Comment by jberkel** [comment]
? don't understand - i meant the submodule in https://github.com/emaloney/CleanroomLogger/tree/swift3/Libraries

**Comment by emaloney** [comment]
I just meant that I had other changes pending on the `swift3` branch of CleanroomLogger that I hadn't yet pushed, including how CleanroomASL was integrated as a submodule. The directory location of the submodule has moved, which may cause an issue if you don't `git submodule init` and `git submodule update`.

Anyway, I've pushed the changes to CleanroomLogger, so please let me know how it goes.

**Comment by jberkel** [comment]
thanks! next error:

```
CleanroomLogger/Sources/ASLLogRecorder.swift:152:35: error: assigning non-escaping parameter 'translator' to an @escaping closure
```

**Comment by emaloney** [comment]
Odd, I guess something was cached since it compiled for me the first time. Anyway, pushed a fix. Should work now.

**Comment by jberkel** [comment]
OK, everything compiles fine now, thanks for your quick help. Will let you know if I run into more problems.
