### ISSUE TITLE
Carthage could not build CleanroomASL 2.0.

### ISSUE THREAD

**Issue by r-plus** [emaloney/CleanroomASL#15]
Hi.

CleanroomASL and CleanroomLogger are not build with Carthage.

carthage version is 0.18.1
Xcode version 8.0(8A218a)

This is error output.

```
$ carthage update CleanroomASL --platform iOS
*** Checking out CleanroomASL at "2.0.0"
*** xcodebuild output can be found in /var/folders/mj/5zhy3sh11h18pdwrb4v04b300000gn/T/carthage-xcodebuild.sdGbmO.log
A shell task (/usr/bin/xcrun xcodebuild -project /Users/taiki/Desktop/clone/HandsPOS.swift3/Carthage/Checkouts/CleanroomASL/CleanroomASL.xcodeproj -scheme CleanroomASL-OSX -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme CleanroomASL-OSX is not currently configured for the clean action.
```

I change Cartfile.resolve commit hash to below 2cases. 

- 13481a1747e8e2f9a92ecd0d087be7d352a637ce then checkout and build are success.
- 0c70c07a17c42ed870f2769aa09b0123800e8836 is failed.

So I thinking this commit(`update for universal framework`) is breaking carthage build.
Maybe also CleanroomLogger.

**Comment by emaloney** [comment]
Thanks for the report. Something seems a little strange with how Carthage is behaving here. First, you're specifying `--platform iOS` but Carthage is attempting to build using the `CleanroomASL-OSX` scheme.

Secondly, while previous CleanroomASL releases used platform-specific schemes, the new release has a single build scheme: `CleanroomASL`, which is what Carthage *should* be using to build.

I'll look into it on my end, but I'm wondering if Carthage has an old copy of the repo cached. It shouldn't be trying to build with `CleanroomASL-OSX` with the universal framework version. So would you mind trying a couple things in the meantime?

First, you can delete the repo from Carthage's cache:

```bash
rm -rf ~/Library/Caches/org.carthage.CarthageKit/dependencies/Cleanroom*
```

and also from your project's `Carthage/Checkouts` directory. Then, try again. It may work.

If it doesn't, there is also some sort of Carthage cache database that may need cleanup:

```bash
rm -rf ~/Library/Caches/carthage
```

Please let me know if any of these remedies work. Thanks!

**Comment by emaloney** [comment]
As a test, I created a new directory and put in the `Cartfile`:

```
github "emaloney/CleanroomASL" ~> 2.0.0
```

Then, I did:

```bash
carthage update
```

and got the result:

```
*** Fetching CleanroomASL
*** Checking out CleanroomASL at "2.0.0"
*** xcodebuild output can be found in /var/folders/gn/gt76_ktx7w1010xg4v68p3txynz8ws/T/carthage-xcodebuild.NpizXz.log
*** Building scheme "CleanroomASL" in CleanroomASL.xcodeproj
```

Success!

Then, I cleared everything out with:

```bash
rm -rf Carthage Cartfile.resolved
```

and tried:

```bash
carthage update --platform iOS
```

and got the same result:

```
*** Fetching CleanroomASL
*** Checking out CleanroomASL at "2.0.0"
*** xcodebuild output can be found in /var/folders/gn/gt76_ktx7w1010xg4v68p3txynz8ws/T/carthage-xcodebuild.PnLwUy.log
*** Building scheme "CleanroomASL" in CleanroomASL.xcodeproj
```

Finally, I tried putting both CleanroomASL and CleanroomLogger in the `Cartfile`:

```
github "emaloney/CleanroomASL" ~> 2.0.0
github "emaloney/CleanroomLogger" ~> 3.0.0
```

and then did:

```bash
rm -rf Carthage Cartfile.resolved
carthage update --platform iOS
```

Success again:

```
*** Fetching CleanroomLogger
*** Fetching CleanroomASL
*** Checking out CleanroomASL at "2.0.0"
*** Checking out CleanroomLogger at "3.0.0"
*** xcodebuild output can be found in /var/folders/gn/gt76_ktx7w1010xg4v68p3txynz8ws/T/carthage-xcodebuild.ESw7Ry.log
*** Building scheme "CleanroomASL" in CleanroomASL.xcodeproj
*** Building scheme "CleanroomLogger" in CleanroomLogger.xcworkspace
```

Given this, I'm guessing the issue is local to your machine, but it might also be the result of a bug in Carthage if the problem is with stale caches not being updated.

If there's any other info you can provide about your installation that would help us file a bug report, I'd like to make sure we follow up by opening a Carthage issue. For example:

- The version of Carthage you're using
- The contents of your `Cartfile` (or at least how CleanroomASL and CleanroomLogger are listed if you're not able to share it entirely)
- The version of Xcode you're using
- The version of macOS your machine is running

**Comment by r-plus** [comment]
Hi, thanks for your quickly reply.

I just try on my home mac(Sierra), then result is success!
Both mac have same version of carthage(0.18.1) and Xcode8(8A218a), but build failed macOS is El Capitan.

```
$ cat Cartfile
github "emaloney/CleanroomLogger" ~> 3.0.0
$ carthage update --platform iOS
*** Fetching CleanroomLogger
*** Fetching CleanroomASL
*** Checking out CleanroomASL at "2.0.0"
*** Checking out CleanroomLogger at "3.0.0"
*** xcodebuild output can be found in /var/folders/5t/h_x9sc_13756x03977z5l58r0000gn/T/carthage-xcodebuild.N0wCbl.log
*** Building scheme "CleanroomASL" in CleanroomASL.xcodeproj
*** Building scheme "CleanroomLogger" in CleanroomLogger.xcworkspace
```

So this issue is only my business mac(El Capitan) as you indicated, I'll try again on business mac at tomorrow and report here.
Cause of issue is probably that I often switch Xcode version (xcode-select) to build carthage for Swift 3(Xcode 8) project and Swift 2.2(Xcode 7.3.1) project.

**Comment by r-plus** [comment]
Hi.

I remove carthage cache and already checkout and build files.

```
rm -rf ~/Library/Caches/org.carthage.CarthageKit/dependencies/Cleanroom*
rm -fr Carthage/Build/iOS/Cleanroom*
rm -fr Carthage/Checkout/Cleanroom*
```

Thus `carthage update` is succeeded, perhaps cause is cache of carthage.

Thanks for your support.
