### ISSUE TITLE
Usage of the new apple logging framework

### ISSUE THREAD

**Issue by matzino** [emaloney/CleanroomASL#17]
Maybe you already discussed that, but exists a reason why you don't use the new apple logging framework os_log? The minimum deployment target must than increased to iOS 10!

This also hides per default private informations within the logging message.

Apple Documentation: https://developer.apple.com/reference/os/1891852-logging

Example Swift implementation:
https://developer.apple.com/library/content/samplecode/Logging/Listings/Paper_Company__Swift__Paper_Company__Swift__ViewController_swift.html#//apple_ref/doc/uid/TP40017510-Paper_Company__Swift__Paper_Company__Swift__ViewController_swift-DontLinkElementID_14

**Comment by emaloney** [comment]
This project is now deprecated as a result of Apple's deprecation of the ASL subsystem.

Closing ticket.

**Comment by emaloney** [comment]
Hello, [CleanroomLogger 5.0](https://github.com/emaloney/CleanroomLogger/releases/tag/5.0.0) has just been released; it now supports Apple's new Unified Logging System.
