### ISSUE TITLE
8.1 iOS Deployment Target

### ISSUE THREAD

**Issue by gragera** [emaloney/CleanroomASL#3]
Hi!

I'm trying to use CleanroomLogger in one of my projects and found out the 8.1 minimum version. What's the reason behind that? I've run the CleanroomASL tests with 8.0 and they work perfectly

Thanks!

**Comment by emaloney** [comment]
Hello,

Thanks for the tip.

Unfortunately, my version of Xcode (6.3.2) does not include an iOS 8.0 simulator, and one does not seem to be available for download either.

I had assumed the reason for the unavailability of an iOS 8.0 simulator was that Swift 1.2 was only compatible with iOS 8.1 and higher.

Can you vouch for the fact that both CleanroomASL and CleanroomLogger build under iOS 8.0? And that the results of running the (meager supply of) unit tests under iOS 8.0 is no different than under 8.1 or higher?

If so, I'll take your word for it and publish new versions of both with Xcode project files set for iOS 8.0 compatibility.

Evan
