### ISSUE TITLE
Project "CleanroomASL.xcodeproj" has no shared schemes

### ISSUE THREAD

**Issue by vishal052** [emaloney/CleanroomASL#5]
I was trying to install the CleanroomLogger on Xcode 7 beta-6 by using Carthage. But after the "carthage update" i am receiving this error and the Build folder is empty i.e no framework files has been generated.

Here is what the terminal looks like::

vishalthakur@Vishals-MBP:~/SourceCode/iOS/WMTasks/LoggerSample/CleanRoomLogger$ carthage update
*** Fetching CleanroomASL
*** Checking out CleanroomASL at "1.2.3"
*** xcodebuild output can be found in /var/folders/x2/p96qt0mn6jqcn9n6tkpt6wc80000gn/T/carthage-xcodebuild.iOvhRD.log
Project "CleanroomASL.xcodeproj" has no shared schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/emaloney/CleanroomASL/issues/new

**Comment by emaloney** [comment]
Hmmm...that's strange. I am not seeing this issue. Would you mind listing the following directory within your project root and let me know what you see:

```bash
cd Carthage/Checkouts/CleanroomASL/CleanroomASL.xcodeproj/xcshareddata/xcschemes
ls -1
```

(That last character is the digit One, not a lowercase L.)

You should see:

```bash
CleanroomASL OSX.xcscheme
CleanroomASL iOS.xcscheme
```

I should note that I haven't tried this with Xcode 7 beta 6 yet—downloading now—so it is possibly related to that.

**Comment by vishal052** [comment]
Here is the output: 

vishalthakur@Vishals-MBP:~/SourceCode/iOS/WMTasks/LoggerSample/CleanRoomLogger/Carthage/Checkouts/CleanroomASL/CleanroomASL.xcodeproj/xcshareddata/xcschemes$ ls -1
CleanroomASL OSX.xcscheme
CleanroomASL iOS.xcscheme

**Comment by emaloney** [comment]
Thanks. It looks like the schemes are there. Having just tried it with Xcode 7 beta 6, it looks like there's a (possibly separate) issue is that the Swift language has changed again between betas, and I am unable to compile for this reason. I'll prepare a new release to fix that.

In the meantime, how are you referencing this in your `Cartfile`? There may be something else amiss that I'll want to look into.

**Comment by uny** [comment]
Same problem...

My Xcode 7 GM can build CleanroomASL (1.3.1), but `carthage bootstrap --platform iOS` says below:

```
Failed to discover shared schemes in project CleanroomASL.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/emaloney/CleanroomASL/issues/new
```

**Comment by emaloney** [comment]
The error being given by Carthage is definitely wrong; the scheme files are appearing in your checkout. Something else must be up...

Would you mind trying this in your `Cartfile` and letting me know if it works:

```
github "emaloney/CleanroomLogger" "xcode7-beta5"
```

**Comment by uny** [comment]
Sadly, I got the same error for "xcode7-beta5" and "1.4.3".

**Comment by emaloney** [comment]
What version of Carthage are you running? You can find out with the command:

```bash
carthage version
```

I am on 0.8.0 currently.

**Comment by uny** [comment]
I am also on 0.8.0.
I reinstalled Xcode and Carthage, created new project, and could build another Carthage project (Realm) successfully.
However, I had the same error for Cartfile:

```
github "emaloney/CleanroomLogger" "xcode7-beta5"
```

**Comment by vishal052** [comment]
I suggest we should test the same on the next release of the Xcode i.e on 16 Sept 2015 and come back with the results as there might be some minor issues in the beta release.

**Comment by uny** [comment]
Yes. I will report the results after that.

**Comment by emaloney** [comment]
I have seen issues with Carthage sometimes failing when scheme names have spaces in them. So, I've updated the `master` branch with new build schemes that have hyphens instead.

If you update your `Cartfile` to:

```
github "emaloney/CleanroomLogger" "master"
```

And try running:

```bash
carthage bootstrap --platform iOS
```

Let me know if you have any luck. If so, I'll publish a new release from `master`.

Incidentally, there seem to be a few other issues with Carthage that are preventing watchOS builds from completing.

**Comment by uny** [comment]
On Xcode7, I could successfully `carthage bootstrap --platform iOS` for the both of `xcode7-beta5` and `master`.
Thank you for your support.

**Comment by vishal052** [comment]
Hard Luck I'm still facing the same

vishalthakur@Vishals-MBP:~/SourceCode/iOS/WMTasks/Sample/CRUptLogger$ open -a Xcode-beta Cartfile
vishalthakur@Vishals-MBP:~/SourceCode/iOS/WMTasks/Sample/CRUptLogger$ carthage bootstrap --platform iOS
*** No Cartfile.resolved found, updating dependencies
*** Fetching CleanroomLogger
*** Fetching CleanroomASL
*** Checking out CleanroomLogger at "fbbccffe8b1abd63b7a65455241503655100e3a6"
*** Checking out CleanroomASL at "1.3.3"
*** xcodebuild output can be found in /var/folders/x2/p96qt0mn6jqcn9n6tkpt6wc80000gn/T/carthage-xcodebuild.PsZk5M.log
Failed to discover shared schemes in project CleanroomASL.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/emaloney/CleanroomASL/issues/new

**Comment by vishal052** [comment]
Here is what I got now
The following build commands failed:
	CompileSwift normal x86_64 /Users/vishalthakur/SourceCode/iOS/WMTasks/Sample/CRUptLogger/Carthage/Checkouts/CleanroomASL/Code/ASLClient.swift
	CompileSwift normal x86_64 /Users/vishalthakur/SourceCode/iOS/WMTasks/Sample/CRUptLogger/Carthage/Checkouts/CleanroomASL/Code/ASLObject.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)
<unknown>:0: error: cannot load underlying module for 'CoreGraphics'
/Users/vishalthakur/SourceCode/iOS/WMTasks/Sample/CRUptLogger/Carthage/Checkouts/CleanroomASL/Code/ASLObject.swift:285:39: error: use of undeclared type 'OptionSetType'
/Users/vishalthakur/SourceCode/iOS/WMTasks/Sample/CRUptLogger/Carthage/Checkouts/CleanroomASL/Code/ASLClient.swift:27:28: error: use of undeclared type 'OptionSetType'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/vishalthakur/SourceCode/iOS/WMTasks/Sample/CRUptLogger/Carthage/Checkouts/CleanroomASL/Code/ASLClient.swift
	CompileSwift normal x86_64 /Users/vishalthakur/SourceCode/iOS/WMTasks/Sample/CRUptLogger/Carthage/Checkouts/CleanroomASL/Code/ASLObject.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)

**Comment by emaloney** [comment]
It looks like Carthage is attempting to compile with the old version of Swift.

What's the output of `xcode-select -p` on your machine?

I've also found that nuking your `Cartfile.resolved` and `Carthage` directory can resolve odd problems with Carthage.

**Comment by vishal052** [comment]
Thanks for the support
