### ISSUE TITLE
The project does not build in Carthage in Xcode 7.0 GM, since it has the tvOS scheme shared.

### ISSUE THREAD

**Issue by bojan** [emaloney/CleanroomASL#6]
Commit e5a351a46de2a8a5a8b7fcb869e1a6ae8b2d6e65 adds support for tvOS, though this target is not supported by Xcode 7.0, only by Xcode 7.1 which is in beta.
As this is a shared scheme, the project fails building using Carthage.

**Comment by emaloney** [comment]
Hi Bojan,

You can avoid the tvOS target by having Carthage build for your specific platform, eg.:

```bash
carthage update --platform iOS
```

or by locking against an earlier release in your `Cartfile`:

```
github "emaloney/CleanroomASL" == 1.2.3
```

Please let me know if this works for you.

E.

**Comment by Dwar3xwar** [comment]
Thanks, it works just fine for me!

**Comment by bojan** [comment]
@emaloney I've tried locking against a earlier release, though I have to admit the version tags are a bit messy. There's a release 1.3.0 b15, then 1.3.0 b14, then 1.3.0 b15. :smile: 
So, I had to select a specific commit hash, not a version. Now, it works.
