### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by lfarah** [emaloney/CleanroomASL#9]
I'd be cool to also add CocoaPods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by Daij-Djan** [comment]
second. I made this into a local pod for now

**Comment by emaloney** [comment]
This project is now deprecated as a result of Apple's deprecation of the ASL subsystem.

Closing ticket.
